---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Robin.
--- DateTime: 2/9/2022 11:55 PM
---

local constants = {
    CardFullName = "AIZ.Card",
    PhoneFullName = "AIZ.Phone",
    VisaFullName = "AIZ.Visa",
    PhoneBodyLocation = "AIZ_Phone_Body_Location",
    OnPhoneEquipChangedEvent = "AIZ_OnPhoneEquipChanged"
}

return constants