---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Robin.
--- DateTime: 2/13/2022 11:54 AM
---

local ui_utils = {}


function ui_utils.VisaDurationToString(duration_minutes)
    local days = math.floor(duration_minutes / 1440)
    local leftover_minutes = duration_minutes % 1440
    local hours = math.floor(leftover_minutes / 60)
    local mins = duration_minutes - (days*1440) - (hours*60)

    return days .. " Day(s) " .. hours .. " Hour(s) " .. mins .. " Minute(s)"
end


return ui_utils