---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Robin.
--- DateTime: 2/10/2022 10:39 AM
---

local playerData = {}


local default = {
    is_playing = false,
    visa_duration = 4320
}

function playerData.GetModData(player)
    if not player then
        player = getPlayer()
    end

    local playerModData = player:getModData()
    if not playerModData.AIZ then
        playerModData.AIZ = default
    end

    return playerModData.AIZ
end

function playerData.GetPlaying(player)
    return playerData.GetModData(player).is_playing or default.is_playing
end

function playerData.SetPlaying(player, is_playing)
    playerData.GetModData(player).is_playing = is_playing
end

function playerData.GetVisaDuration(player)
    return playerData.GetModData(player).visa_duration or default.visa_duration
end

function playerData.SetVisaDuration(player, duration)
    playerData.GetModData(player).visa_duration = duration
end

return playerData