---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Robin.
--- DateTime: 2/9/2022 11:55 PM
---

local Constants = {
    Card = "AIZ.Card",
    Phone = "AIZ.Phone",
    Visa = "AIZ.Visa",
    PhoneBodyLocation = "AIZ_Phone_Body_Location",
}

return Constants