---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Robin.
--- DateTime: 2/10/2022 9:25 AM
---

AcceptItemFunction = AcceptItemFunction or {}

---@param item AliasItem
function AcceptItemFunction.AIZ_Phone(container, item)
    return AIZMod.Shared.InventoryUtils.DoesPhoneAcceptItem(item)
end
