---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Robin.
--- DateTime: 2/10/2022 9:25 AM
---

AcceptItemFunction = AcceptItemFunction or {}

local inventory_utils = require('InventoryUtils')

---@param item AliasItem
function AcceptItemFunction.Phone(container, item)
    return inventory_utils.DoesPhoneAcceptItem(item)
end
