---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Robin.
--- DateTime: 2/11/2022 10:42 AM
---


AIZMod.Log("OnPhoneEquipChanged Init")

local inventory_utils = AIZMod.Shared.InventoryUtils

local ISWearClothing_perform = ISWearClothing.perform;
function ISWearClothing:perform(...)
    ISWearClothing_perform(self, ...);

    if inventory_utils.IsPhone(self.item) then
        triggerEvent("AIZ_OnPhoneEquipChanged", self.character, self.item, true);
    end

end

local ISUnequipAction_perform = ISUnequipAction.perform;
function ISUnequipAction:perform(...)
    ISUnequipAction_perform(self, ...);
    if inventory_utils.IsPhone(self.item) then
        triggerEvent("AIZ_OnPhoneEquipChanged", self.character, self.item, false);
    end
end


---@param player AliasPlayer
---@param item AliasItem
local function OnPhoneEquipChanged(player, item, is_equipped)

    AIZMod.Log("On Phone Equip Changed", player, item, is_equipped)
    if  player == nil or item == nil then return end

    if is_equipped then
        player:Say("Playing 'Alice in Zomboidland' ! Need to check my Visa expiration time !")
    else
        player:Say("Not playing 'Alice in Zomboidland' anymore...")
    end
end


Events.AIZ_OnPhoneEquipChanged.Add(OnPhoneEquipChanged);

----- We check if the player is wearing the Phone
-----@param player AliasPlayer
--local function CheckIfPlayingMod(player)
--    if player == nil then   return  end
--
--
--    local phone = inventory_utils.GetEquippedPhone(player)
--
--    if phone == nil then
--        player:Say("Not playing 'Alice in Zomboidland' anymore...")
--        player_data.SetPlaying(player, false)
--    else
--        player:Say("Playing 'Alice in Zomboidland' ! Need to check my Visa expiration time !")
--        player_data.SetPlaying(player, true)
--    end
--
--end
--
--
--local function Init()
--    Events.OnTick.Remove(Init);
--    local player = getPlayer()
--    CheckIfPlayingMod(player)
--    print("AIZ: First Tick")
--end

--
--
--Events.OnTick.Add(Init);