---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Robin.
--- DateTime: 2/12/2022 3:20 PM
---



local inventory_utils = AIZMod.Shared.InventoryUtils
local player_data = AIZMod.Shared.PlayerData
local ui_utils = AIZMod.Shared.UIUtils

---@param item AliasItem
---@param player AliasPlayer
local function OnVisaUsedFromContextMenu(item)

    local player = getPlayer()

    if player == nil then
        return
    end

    local player_visa_duration = player_data.GetVisaDuration(player)
    local item_visa_duration = inventory_utils.GetVisaDuration(item)

    AIZMod.Log("Using Visa", item)

    AIZMod.Log("Current Player Visa Duration", player_visa_duration)
    AIZMod.Log("Visa Item Duration", item_visa_duration)

    local new_player_visa_duration = player_visa_duration + item_visa_duration

    AIZMod.Log("New Player Visa", new_player_visa_duration)
    player_data.SetVisaDuration(player, new_player_visa_duration )

    player:getInventory():DoRemoveItem(item)

end

local function OnFillInventoryObjectContextMenu(player, context, items)
    ---@type AliasItem
    local item
    if items[1].items then
        item = items[1].items[1]
    else -- if right-clicked in hotbar
        item = items[1]
    end

    if item == nil then
        return
    end

    if  inventory_utils.IsVisa(item)  then
        local visa_duration = inventory_utils.GetVisaDuration(item)

        option = context:addOption("Use Visa " .. "(" .. ui_utils.VisaDurationToString(visa_duration) .. ")" , item, OnVisaUsedFromContextMenu);
    end
    --for _, _items in ipairs(items) do
    --    if instanceof(_items, "HandWeapon") then
    --        local option = context:addOption("Context option title", _items, functionToCallOnItem);
    --        break;
    --    else
    --        for j, item in ipairs(items) do
    --            if instanceof(item, "HandWeapon") then
    --                local option = context:addOption("Context option title", item, functionToCallOnItem);
    --                break;
    --            end
    --        end
    --    end
    --end
end
Events.OnFillInventoryObjectContextMenu.Add(OnFillInventoryObjectContextMenu);



local ISToolTipInvRender_OLD = ISToolTipInv.render;
function ISToolTipInv:render()
    if inventory_utils.IsVisa(self.item) then
        local visa_duration = inventory_utils.GetVisaDuration(self.item)
        self.item:setTooltip("Visa Duration: " .. ui_utils.VisaDurationToString(visa_duration));
    elseif inventory_utils.IsPhone(self.item) then
        local visa_duration = player_data.GetVisaDuration(getPlayer())
        self.item:setTooltip("Visa Duration: " .. ui_utils.VisaDurationToString(visa_duration));
    end

    ISToolTipInvRender_OLD(self);
end